# Generated by Django 5.1.4 on 2025-01-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainImg', models.URLField()),
                ('maintitle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('authorImg', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('reading_time', models.PositiveBigIntegerField(help_text='Reading time in minutes')),
            ],
        ),
    ]
