# Generated by Django 5.1.4 on 2025-01-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogApp', '0003_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='dob',
            new_name='dateObirth',
        ),
    ]
